apiVersion: v1
kind: Service
metadata:
  name: flashcard-service
spec:
  type: LoadBalancer
  selector:
    app: flashcard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5010
